# Generated by Django 3.0.3 on 2020-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.CharField(default='Ayan Agrawal', max_length=100),
            preserve_default=False,
        ),
    ]
